name: amber_nn
channels:
  - conda-forge
  - default
dependencies:
  - python=3.7
  - ipykernel
  - numpy
  - pandas
  - scipy
  - matplotlib-base
  - dask
  - toolz
  - xarray
  - scikit-learn
  - ase
  - netCDF4
  - pip
  - pip:
    - tensorflow==2.1
    - spektral
